services:
  - type: web
    name: CRYPTEX
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn obfuscation:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
